### ISSUE TITLE
Folder and doc reorganizaton

### ISSUE THREAD

**Issue by makruger** [makruger/website-2.0#15]
Having a lingering feeling we're going to want to move a few things around and should do it now rather than later. Here are some thoughts on this content reorg.

The doc\notes folder currently contains:
* Doc Team Notes (strategic guidance for moving foward)
* OI FAQ
* OI Code of Conduct
* OI Handbook (along with it's image folder). 

I would like to see these docs moved:

* FAQ
* Code of conduct
* Userland

FAQ to have it's own button - docs\faq.md
Code of conduct moved to docs\misc\conduct.md
Userland move to docs\dev\userland.md

The handbook I think should be moved to it's own folder along with it's image folder. This will end up looking like:

* docs\handbook
* docs\handbook\images). 

These changes would leave the notes folder containing.....well, notes.

While we're at it.......now that the contrib doc is a single file, lets rename it to contrib.md and move it to the root of docs. Then remove the contrib folder.

**Comment by AdrianKoshka** [comment]
also:

- update the menus to reflect the changes

as you said on IRC.

**Comment by makruger** [comment]
completed....and even fixed the favicon.
