### ISSUE TITLE
Describe folder structure and mkdocs.yml

### ISSUE THREAD

**Issue by makruger** [makruger/website-2.0#38]
Somewhere, perhaps here: http://makruger.github.io/website-2.0/contrib/getting-started/#make-some-changes, perhaps elsewhere (tools, style guide, not sure), we need to describe the folder structure and how to add pages to the menu file mkdocs.yml.

* [x] Added folder structure with a nice table providing descriptions.

Remaining work:
* [x] Describe how to add pages to mkdocs.yml
* [x] Describe how to reference other pages.
This last one is handled via the 'internal url's section of the markdown guide'

**Comment by makruger** [comment]
[x] Added folder structure with a nice table providing descriptions.

Remaining work:
[ ] Describe how to add pages to mkdocs.yml

**Comment by AdrianKoshka** [comment]
@makruger think you mean to do

```
* [x] Added folder structure with a nice table providing descriptions.

Remaining work:
* [ ] Describe how to add pages to mkdocs.yml
```

* [x] Added folder structure with a nice table providing descriptions.

Remaining work:
* [ ] Describe how to add pages to mkdocs.yml

**Comment by makruger** [comment]
Yep....that was it. Thanks!
