### ISSUE TITLE
Show how to use spell check, etc.

### ISSUE THREAD

**Issue by makruger** [makruger/website-2.0#42]
Add to getting started page:

* [x] Provide instructions for using the spell check tool. 
* [x] Show how to turn on spell check in VIM.
    * Enable spell check from command mode using `:set spell spelllang=en_us`
    * Enable in `.vimrc` by adding `set spell spelllang=en_us`
    * Misspelled words are highlighted in red.
    * Use hotkeys `]s` and `[s` to find next word.
    * With the cursor at the beginning of a word, use the hotkeys `z=` to bring up suggested replacements.
    * Use hotkey `zg` to add a word to the local dictionary exception file.
    * Use hotkeys `zw` to mark a word as incorrect.

**Comment by AdrianKoshka** [comment]
Taken care of by #51

**Comment by makruger** [comment]
Looks good...thank you !
