### ISSUE TITLE
describe the rational behind the content review process (PR's)

### ISSUE THREAD

**Issue by makruger** [makruger/website-2.0#43]
Come up with a list of reasons for why the docs sub-project (openindiana.org) follows the PR process instead of simply giving everyone unrestricted commit rights to the repository.

* Ensures doc team leader knows what's being contributed.
* Ensures consistent style
* Ensures content is correctly located.
* Ensure changes actually work (Are factually correct, have been peer reviewed, etc.)

**Comment by AdrianKoshka** [comment]
> Ensure changes actually work (have been tested, etc.)

While travis will do this for the most part for us, manual content review is still always a good thing to do :)

**Comment by makruger** [comment]
What I meant here is performing a technical review to ensure the content of the text (the guidance we are providing the OI end user in the form of documentation) is factually correct and actually works. This would be similar to performing a peer review of code.
