### ISSUE TITLE
sudo command will not work

### ISSUE THREAD

**Issue by pyhalov** [makruger/website-2.0#46]
https://github.com/makruger/website-2.0/blob/master/docs/handbook/handbook.md
sudo echo 'nameserver 192.168.1.121' >> /etc/resolv.conf will not work, as last redirection is executed as user

**Comment by AdrianKoshka** [comment]
In the future providing a link with the header anchor will help us find the section you're talking about.
e.g.

https://github.com/makruger/website-2.0/blob/master/docs/handbook/handbook.md#manual-configuration-static-ip

allows me to look at the problem faster then just giving the link to the whole handbook.

**Comment by makruger** [comment]
Easy way to grab those sectional title URL's is right clicking and copying the corresponding entry from the menu on the left side of the page. That should get us pretty close. We'll probably add this tip to the issue we have open for describing the process of opening issues;-)

**Comment by shaggytwodope** [comment]
sudo sh -c 'echo "nameserver 192.168.1.121" >> /etc/resolv.conf'

is one solution to this

**Comment by AdrianKoshka** [comment]
While I don't have an OI instnace to test what @shaggytwodope said, I'm going to go ahead and apply his solution, if anyone else doesn't have a problem with this.

**Comment by AdrianKoshka** [comment]
#55 should fix @pyhalov's issue
