### ISSUE TITLE
Make notes about working with markdown

### ISSUE THREAD

**Issue by AdrianKoshka** [makruger/website-2.0#6]
Makes a set of notes similar to the ones we have now for working with
asciidoctor, but for working with markdown.

**Comment by makruger** [comment]
Yep, good idea. We can rework, replace, create new files as needed. No need to retain anything asciidoctor specific, or even Sphinx specific as all that information safely resides in my other repositories.

**Comment by makruger** [comment]
We've pretty much got this covered now...
